export default {
  MARKET_MAKING_SPREAD_CHANGED: 'MARKET_MAKING_SPREAD_CHANGED',
  BALANCE_RATE_CHANGED: 'BALANCE_RATE_CHANGED',
  BALANCING_AGGRESSION_CHANGED: 'BALANCING_AGGRESSION_CHANGED',
  DAI_PRICES: 'DAI_PRICES',
  WITHDRAWAL_AMOUNT_CHANGED: 'WITHDRAWAL_AMOUNT_CHANGED',
  ROUND_INFO_RECEIVED: 'ROUND_INFO_RECEIVED',
  KILL_CONSENSUS_RECEIVED: 'KILL_CONSENSUS_RECEIVED',
  TAP_CONSENSUS_RECEIVED: 'TAP_CONSENSUS_RECEIVED',
  CURRENT_TAP_RECEIVED: 'CURRENT_TAP_RECEIVED',
  REMAINING_BALANCE_RECEIVED: 'REMAINING_BALANCE_RECEIVED',
  MANUAL_AGGRESSION_CHANGED: 'MANUAL_AGGRESSION_CHANGED',
  DAI_PRICES_ERROR: 'DAI_PRICES_ERROR'
};
