export default {
  MARKET_MAKING_SPREAD_CHANGED: 'MARKET_MAKING_SPREAD_CHANGED',
  BALANCE_RATE_CHANGED: 'BALANCE_RATE_CHANGED',
  BALANCING_AGGRESSION_CHANGED: 'BALANCING_AGGRESSION_CHANGED',
  DAI_PRICES: 'DAI_PRICES',
  WITHDRAWAL_AMOUNT_CHANGED: 'WITHDRAWAL_AMOUNT_CHANGED',
  ROUND_INFO_RECEIVED: 'ROUND_INFO_RECEIVED'
};
